### ISSUE TITLE
Not a coder

### ISSUE THREAD

**Issue by sanganisahil** [tencent-ailab/V-Express#11]
Hi I'm not a coder, can you tell me if any space is there that i can use?

**Comment by FurkanGozukara** [comment]
i made auto installer and gradio app https://www.patreon.com/posts/105251204

![interface](https://github.com/tencent-ailab/V-Express/assets/19240467/3e7c34a3-ebb7-444d-9480-cc53e19a7c2d)

https://github.com/tencent-ailab/V-Express/assets/19240467/e76a9b48-4635-4cad-87fc-155003ddbec2

**Comment by cantonalex** [comment]
Can we delete this patreon crap. It goes against everything open source. The Vexpress team have open sourced the code. Don't then take it and try and monetise it by putting it on HF.
Here is an open source version of HF https://huggingface.co/spaces/alexcanton/V-Express/ requires GPU for runtime

**Comment by faraday** [comment]
@cantonalex I also tried to prepare a Gradio app here: https://huggingface.co/spaces/faraday/V-Express

Refactored the code a bit, to make it slightly more understandable and directly callable as functions.

Modified inference.py to have an **InferenceEngine** class that keeps required models loaded when Gradio app.py starts.
Refactor kps sequence extraction script as extract_kps_sequence_from_video function from sequence_utils.

The idea was to serve subsequent inference requests without model loads every time.

**Comment by cantonalex** [comment]
@faraday do you know how you can export the video without the crop onto the source video? https://github.com/tencent-ailab/V-Express/issues/9
