### ISSUE TITLE
the value of reference_attention_weight and audio_attention_weight in training?

### ISSUE THREAD

**Issue by saeedfirouzi** [tencent-ailab/V-Express#12]
thanks for your great work.
what is the value of reference_attention_weight and audio_attention_weight in training?
is it a static parameter or it is a random number in a specific range?

**Comment by Tenvence** [comment]
The parameters `reference_attention_weight` and `audio_attention_weight` are only considered during inference. 

For training, we disregard the variation of these parameters and set both to 1.0.

**Comment by saeedfirouzi** [comment]
so can you explain about this method of "progressive drop operations" : 
 a simple method that balances different control signals through a series of progressive drop operations.

**Comment by saeedfirouzi** [comment]
yeah, after reading the article I found the answer.
