### ISSUE TITLE
xformers is not available

### ISSUE THREAD

**Issue by jkla139** [tencent-ailab/V-Express#15]
提示xformers不可用，pip install xformers，然后cuda全家桶安装一遍，最后提示类似内存格式错误的信息。
下面是没安装xformers前提示的错误：

Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with: 

pip install accelerate

Some weights of the model checkpoint at ./model_ckpts/wav2vec2-base-960h/ were not used when initializing Wav2Vec2Model: ['lm_head.bias', 'lm_head.weight']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at ./model_ckpts/wav2vec2-base-960h/ and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/root/miniconda3/lib/python3.10/site-packages/diffusers/configuration_utils.py:240: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a model, please use <class 'modules.unet_2d_condition.UNet2DConditionModel'>.load_config(...) followed by <class 'modules.unet_2d_condition.UNet2DConditionModel'>.from_config(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
Loaded weights of Reference Net from ./model_ckpts/v-express/reference_net.pth.
Loaded weights of Denoising U-Net from ./model_ckpts/v-express/denoising_unet.pth.
Loaded weights of Denoising U-Net Motion Module from ./model_ckpts/v-express/motion_module.pth.
Loaded weights of V-Kps Guider from ./model_ckpts/v-express/v_kps_guider.pth.
Loaded weights of Audio Projection from ./model_ckpts/v-express/audio_projection.pth.
Traceback (most recent call last):
  File "/root/V-Express/inference.py", line 275, in <module>
    main()
  File "/root/V-Express/inference.py", line 171, in main
    raise ValueError("xformers is not available. Make sure it is installed correctly")
ValueError: xformers is not available. Make sure it is installed correctly

**Comment by faraday** [comment]
see https://github.com/tencent-ailab/V-Express/issues/7

**Comment by faraday** [comment]
`pip install xformers==0.0.20`

**Comment by jkla139** [comment]
> `pip install xformers==0.0.20`

Thank you for your good solution!
