### ISSUE TITLE
character expressions

### ISSUE THREAD

**Issue by lifeng5658** [tencent-ailab/V-Express#18]
I think you should focus on facial expressions. The current leading AI in this field, including EMO and vasa, not only focus on lip-sync animations but also have very strong facial muscle movements and rich character expressions. This can be said to contribute to 70% of the final effect. Your research has taken a new direction. ^_^

**Comment by zhangjun001** [comment]
Thanks. If you look at the results carefully, the audio drive itself contains characteristics such as emotions, which can have corresponding facial muscle changes and even laryngeal and cranial movements. Therefore, this type of data-driven model can often learn emotions and other muscle expressions.  
In fact, it is very intuitive to add explicit expression control and other signals. We have also done some experiments and have some results. But these changes sometimes essentially conflict with the expression. For example, a piece of audio itself contains the emotion of anger, but it is forced to express happiness.
