### ISSUE TITLE
V-Express via Gradio Implementation and Acknowledgements

### ISSUE THREAD

**Issue by M4K4R** [tencent-ailab/V-Express#33]
Hi everyone,

I have created a repository to run the V-Express project via Gradio, compiling various resources and code snippets shared by different individuals. The repository is available at the following link:

[Gradio V-Express Project](https://github.com/M4K4R/Gradio-V-Express)

Special thanks to [faraday](https://github.com/faraday) and [NewGenAI](https://www.youtube.com/@StableAIHub) for their invaluable contributions. Their insights and shared code made this implementation possible.

Check out the YouTube video by NewGenAI for more details:
[NewGenAI](https://youtu.be/OFt6a2rR8GY?si=9l6cD1jBZmVexRc-)

Feel free to open issues or submit pull requests if you have any suggestions or questions.

Thank you!

**Comment by nitinmukesh** [comment]
This doesn't work anymore. I have published new video.

Still the following new update is not supported
[2024/06/15] 🔥 We have optimized memory usage, now supporting the generation of longer videos.

**Comment by oisilener1982** [comment]
link for the new tutorial
https://www.youtube.com/watch?v=ttEOIg9j2B4&t=327s
