### ISSUE TITLE
If you have problems with slow start...

### ISSUE THREAD

**Issue by KMiNT21** [tencent-ailab/V-Express#38]
If you encounter a very slow startup, you can safely remove the file **model_ckpts\insightface_models\models\buffalo_l\1k3d68.onnx** (137M)
 
While loading on my PC, this model significantly slows down the process
(model = onnx.load(self.model_file) inside insightface/model_zoo/landmark.py).

However, this project doesn't utilize this model; it relies solely on the RetinaFace 'detection' model (det_10g.onnx). Therefore, removing the unused model eliminates the unnecessary wait during initialization.

**Comment by tiankuan93** [comment]
This file is not being used and I will remove this file from the huggingface repository.
