### ISSUE TITLE
hugging face

### ISSUE THREAD

**Issue by jokedud** [tencent-ailab/V-Express#4]
i tried setting it up in hugging face but didnt work, has anyone set it up there yet? or is it not out yet??

**Comment by tiankuan93** [comment]
We provide the model on the huggingface website and you need to follow the installation steps for offline inference. We don't provide the hugging face demo yet.

**Comment by cantonalex** [comment]
@tiankuan93 can you apply lip sync to destination video. or is it just source image to animated video?

**Comment by faraday** [comment]
from @cantonalex : https://huggingface.co/spaces/alexcanton/V-Express/
from me: https://huggingface.co/spaces/faraday/V-Express (models the required models only at the start, code slightly refactored)

both require GPU runtime

**Comment by jokedud** [comment]
https://huggingface.co/spaces/faraday/V-Express is closed

**Comment by faraday** [comment]
@jokedud You should duplicate the space and set a GPU to run it with.
It costs a lot in my opinion and not suitable to apply ZeroGPU, that's why it's closed.
