### ISSUE TITLE
想问下关于训练的策略

### ISSUE THREAD

**Issue by junwenxiong** [tencent-ailab/V-Express#5]
作者你好，感觉这个工作也是用了多阶段的训练策略，可否说一下在不同的阶段训练时，哪些attention需要被优化？谢谢！

**Comment by tiankuan93** [comment]
> 作者你好，感觉这个工作也是用了多阶段的训练策略，可否说一下在不同的阶段训练时，哪些attention需要被优化？谢谢！

We are working on a technical report in which we will elaborate on the training details. Please be patient for a few more days.
