### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by fotrjhay** [tencent-ailab/V-Express#51]
When trying to load models, PyTorch throws the following error 

"torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 4.00 GiB total capacity; 3.40 GiB already allocated; 0 bytes free; 3.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

**Comment by FurkanGozukara** [comment]
ye you need cloud - your gpu very weak

https://youtu.be/GXBiqJOc9FE

### [**V-Express 1-Click AI Talking Avatar Generator - Like D-ID - Massed Compute, RunPod & Kaggle Guide**](https://youtu.be/GXBiqJOc9FE)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/O-GwtKjvYb3NyI5Lgpf8S.png)](https://youtu.be/GXBiqJOc9FE)

**Comment by fotrjhay** [comment]
Thank you
